spring:
  application:
    name: '@project.artifactId@'
  profiles:
    active: '@spring.profiles.active@'
  datasource:
    url: jdbc:mysql://10.67.64.3:3306/mirante-educacao
    username: root
    password: q%JaJ|Jbr{Ezf\TZ
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MariaDBDialect

info:
  app:
    description: '@project.description@'
    encoding: '@project.build.sourceEncoding@'
  build:
    artifact: '@project.artifactId@'
    group: '@project.groupId@'
    name: '@project.name@'
    description: '@project.description@'
    version: '@project.version@'
server:
  port: 8080
  servlet:
    context-path: /edu-api
  error:
    include-message: always

